version: '3'

services:
  app:
    image: 'codepaste:latest'
    build:
      context: .
    container_name: codepaste-app
    ports:
      - "8889:8889"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8889
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:14-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

